### ISSUE TITLE
Creative Test page inappropriately expands iframe with transition

### ISSUE THREAD

**Issue by andyearnshaw** [InteractiveAdvertisingBureau/safeframe#1]
According to the 1.0.1 version of the spec, for `$.sf.expand()`,

> Tweening or animation is not supported in the SafeFrame so any animation must be processed by the external party within the container and call this method whenever it needs to expand to its maximum size. 

However, in the `creative_test.html` example page, there's a transition set in the styles:

```css
#topAdWrapper div, #topAdWrapper div iframe {
    transition: width 0.4s ease-in-out, height 0.4s;
}
```

Coupled with the alignment changes made by `ext.js`, this causes a leftward expanding ad with its own animation to jump to the left while expanding, giving a false impression that there is a problem with the creative.
